apiVersion: v1
kind: Service
metadata:
  name: sre-demo-service
  namespace: sre-demo
spec:
  type: ClusterIP
  selector:
    app: sre-demo
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    